# Generated by Django 4.1.5 on 2023-05-24 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_deviceinformation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='%d.%m.%Y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='broken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
